/* Safe listing-draft handoff. Nancy alone publishes to eBay. */
(function(){"use strict";
var S="---COMMAND-CENTER-RESULT---",E="---END-COMMAND-CENTER-RESULT---",F=["Title","Brand","Category","Condition","Price","Description","Research notes"],last=null;
function $(x){return document.getElementById(x)} function esc(x){return String(x==null?"":x).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function msg(x){typeof toast==="function"?toast(x):alert(x)}
function details(){return{cost:$("agentCost")?.value.trim()||"",costStatus:$("agentCostStatus")?.value||"unknown",source:$("agentSource")?.value.trim()||"",storage:$("agentStorage")?.value.trim()||"",notes:$("agentNotes")?.value.trim()||""}}
function count(){try{return listingAgentPhotos.length}catch(e){return 0}}
function prompt(){var d=details(),n=count();return ["RESELLER COMMAND CENTER — LISTING DRAFT JOB","","I am attaching "+n+" photo"+(n===1?"":"s")+" of one item.","","What I know:","- Cost: "+(d.cost||"(unknown)")+" ["+d.costStatus+"]","- Source: "+(d.source||"(not recorded)"),"- Storage: "+(d.storage||"(not recorded)"),"- Notes: "+(d.notes||"(none)"),"","Examine every photo. Identify only from visible evidence. Research comparable SOLD listings from public web sources when available. Prepare an eBay-ready title, description, category, condition, brand, and competitive price. Never invent unsupported details. Never expose cost/source/storage in public copy.","","IMPORTANT: Do NOT access, log into, browse, edit, or publish to eBay. Nancy alone handles eBay. This is a draft for review and later inclusion in a Nancy-uploaded eBay file.","","End with this exact block; leave unsupported fields blank.",S,"Title: ","Brand: ","Category: ","Condition: ","Price: ","Description: ","Research notes: ",E].join("\n")}
function send(){if(!count()){msg("Stage this item's photos first.");return} $("museHandoffText").value=prompt();$("museHandoffPanel").hidden=false;if($("museResultPreview"))$("museResultPreview").hidden=true;if($("saveMuseResultBtn"))$("saveMuseResultBtn").disabled=true;$("museHandoffPanel").scrollIntoView({behavior:"smooth",block:"start"});msg("Draft instructions ready.")}
function copy(){var t=$("museHandoffText");if(!t?.value)return; navigator.clipboard?.writeText(t.value).then(()=>msg("Draft instructions copied."),()=>{t.select();document.execCommand("copy");msg("Draft instructions copied.")})}
function parseBlock(t){t=String(t||"");var s=t.lastIndexOf(S),e=t.lastIndexOf(E);return s<0||e<=s?null:t.slice(s+S.length,e).trim()}
function fields(b){var o={};F.forEach(k=>o[k]="");var k=null;b.split(/\r?\n/).forEach(raw=>{var line=raw.trim(),m=line.match(/^([A-Za-z][A-Za-z ]*):\s*(.*)$/);if(m&&F.includes(m[1])){k=m[1];o[k]=m[2].trim()}else if(k&&line)o[k]+="\n"+line});return o}
function preview(){var b=parseBlock($("museResultText")?.value);last=null;if($("saveMuseResultBtn"))$("saveMuseResultBtn").disabled=true;if(!b){$("museResultPreview").hidden=false;$("museResultPreview").innerHTML='<p class="muted">No result block found.</p>';return}var f=fields(b);if(!f.Title){msg("Result block has no title.");return}last=f;$("museResultPreview").hidden=false;$("museResultPreview").innerHTML='<table class="muse-result-table"><tbody>'+F.map(k=>"<tr><th>"+esc(k)+"</th><td>"+esc(f[k]||"—").replaceAll("\n","<br>")+"</td></tr>").join("")+"</tbody></table>";$("saveMuseResultBtn").disabled=false;msg("Draft parsed — review it, then save.")}
function price(x){var n=Number(String(x||"").replace(/[^0-9.]/g,""));return Number.isFinite(n)?n:0}
async function save(){if(!last){msg("Preview the result first.");return}var f=last,d=details(),notes=[];if(f.Description)notes.push(f.Description);if(f["Research notes"])notes.push("Research notes: "+f["Research notes"]);if(f.Condition)notes.push("Condition: "+f.Condition);var item={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),title:f.Title,brand:f.Brand||"",category:f.Category||"",purchaseCost:Number(d.cost||0),costStatus:d.costStatus||"unknown",purchaseDate:"",source:d.source||"",storage:d.storage||"",status:"Unlisted",listPrice:price(f.Price),listedMarketplaces:[],saleMarketplace:"",saleDate:"",salePrice:0,shippingCollected:0,fees:0,shippingCost:0,otherExpenses:0,notes:notes.join("\n\n"),listingDescription:f.Description||"",itemCondition:f.Condition||"",researchNotes:f["Research notes"]||"",draftStatus:"draft"};try{var saved=await saveCloudItem(item);if(typeof listingAgentPhotos!=="undefined"&&listingAgentPhotos.length&&typeof uploadListingPhotos==="function"){try{var paths=await uploadListingPhotos(saved.id,[...listingAgentPhotos]);saved=await saveCloudItem({...saved,listingPhotoPaths:paths});}catch(photoError){console.warn("Draft saved, but photos could not be persisted",photoError);msg("Draft saved, but its photos could not be saved. You can add them again in Master Drafts.");}}items.unshift(saved);renderAll();last=null;$("museResultText").value="";$("museResultPreview").hidden=true;msg("Listing draft saved — photos retained, not published.")}catch(e){$("saveMuseResultBtn").disabled=false;alert("Could not save this draft. "+e.message)}}
function init(){if(!$("sendToMuseBtn"))return;$("sendToMuseBtn").addEventListener("click",send);$("copyMuseHandoffBtn")?.addEventListener("click",copy);$("parseMuseResultBtn")?.addEventListener("click",preview);$("saveMuseResultBtn")?.addEventListener("click",save)}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init();
})();